spring.application.name=cass-example

#Настройки подключения к Cassandra
spring.cassandra.keyspace-name=mobishop
spring.cassandra.local-datacenter=LORDAERON
spring.cassandra.request.timeout=10s
spring.cassandra.request.consistency=QUORUM
spring.cassandra.request.serial-consistency=SERIAL

# для three-node-compose
spring.cassandra.contact-points=172.22.0.11

# для six-node-compose
#spring.cassandra.contact-points=172.21.0.11:9042,172.21.0.12:9042,172.21.0.13:9042
