spring.application.name=cass-example

#Настройки подключения к Cassandra
spring.cassandra.keyspace-name=mobishop
spring.cassandra.contact-points=127.0.0.1:9045
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.request.timeout=10s
spring.cassandra.request.consistency=QUORUM
spring.cassandra.request.serial-consistency=SERIAL
