
#Настройки сети
networks:
  cassandra_six: # docker network where all cassandra nodes will be put in
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
         gateway: 172.21.0.1          

# IP адреса узлов
x-network-ips:
  ip-a: &ip-a 172.21.0.11
  ip-b: &ip-b 172.21.0.12
  ip-c: &ip-c 172.21.0.13
  ip-d: &ip-d 172.21.0.14
  ip-e: &ip-e 172.21.0.15
  ip-f: &ip-f 172.21.0.16
  
# Базовый шаблон
x-cassandra-base: &cassandra-base
  image: cassandra:4.1.11
  healthcheck:
    test: ["CMD-SHELL", "nodetool status | grep -e \"UN.*$${NODE_IP}.*$${CASSANDRA_DC}\""]
    interval: 5s
    timeout: 5s
    retries: 60
  deploy:
    resources:
      limits:
        memory: 512M
        
# Общие переменные окружения
x-environment: &common-env
  CASSANDRA_SEEDS: "cass-six-A:7000,cass-six-D:7000"
  CASSANDRA_CLUSTER_NAME: SIX_CLUSTER
  CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
  JVM_OPTS: "-Xms128M -Xmx256M -XX:+UseG1GC"
  
  
services:
  cass-six-A:
    <<: *cassandra-base
    container_name: cass-six-A
    hostname: cass-six-A
    networks:
      cassandra_six:
        ipv4_address: *ip-a
    ports: ["9041:9042", "7191:7199", "7001:7000"]
    volumes:
      - ./data/cass-six-A:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-a
      CASSANDRA_DC: LORDAERON
      CASSANDRA_RACK: LORDAERON-RACK  
      
  cass-six-B:
    <<: *cassandra-base
    container_name: cass-six-B
    hostname: cass-six-B
    networks:
      cassandra_six:
        ipv4_address: *ip-b
    ports: ["9042:9042", "7192:7199", "7002:7000"]
    volumes:
      - ./data/cass-six-B:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-b
      CASSANDRA_DC: LORDAERON
      CASSANDRA_RACK: LORDAERON-RACK
    depends_on:
      cass-six-A: { condition: service_healthy }
      
  cass-six-C:
    <<: *cassandra-base
    container_name: cass-six-C
    hostname: cass-six-C
    networks:
      cassandra_six:
        ipv4_address: *ip-c
    ports: ["9043:9042", "7193:7199", "7003:7000"]
    volumes:
      - ./data/cass-six-C:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-c
      CASSANDRA_DC: LORDAERON
      CASSANDRA_RACK: LORDAERON-RACK
    depends_on:
      cass-six-B: { condition: service_healthy }
      
  cass-six-D:
    <<: *cassandra-base
    container_name: cass-six-D
    hostname: cass-six-D
    networks:
      cassandra_six:
        ipv4_address: *ip-d
    ports: ["9044:9042", "7194:7199", "7004:7000"]
    volumes:
      - ./data/cass-six-D:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-d
      CASSANDRA_DC: KALIMDOR
      CASSANDRA_RACK: KALIMDOR-RACK
    depends_on:
      cass-six-C: { condition: service_healthy }
      
  cass-six-E:
    <<: *cassandra-base
    container_name: cass-six-E
    hostname: cass-six-E
    networks:
      cassandra_six:
        ipv4_address: *ip-e
    ports: ["9045:9042", "7195:7199", "7005:7000"]
    volumes:
      - ./data/cass-six-E:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-e
      CASSANDRA_DC: KALIMDOR
      CASSANDRA_RACK: KALIMDOR-RACK
    depends_on:
      cass-six-D: { condition: service_healthy }
      
  cass-six-F:
    <<: *cassandra-base
    container_name: cass-six-F
    hostname: cass-six-F
    networks:
      cassandra_six:
        ipv4_address: *ip-f
    ports: ["9046:9042", "7196:7199", "7006:7000"]
    volumes:
      - ./data/cass-six-F:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-f
      CASSANDRA_DC: KALIMDOR
      CASSANDRA_RACK: KALIMDOR-RACK
    depends_on:
      cass-six-E: { condition: service_healthy }
