networks:
  cassandra_three:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

x-network-ips:
  ip-a: &ip-a 172.22.0.11
  ip-b: &ip-b 172.22.0.12
  ip-c: &ip-c 172.22.0.13


# Базовый шаблон
x-cassandra-base: &cassandra-base
  image: cassandra:4.1.11
  healthcheck:
    test: ["CMD-SHELL", "nodetool status | grep -e \"UN.*$${NODE_IP}.*$${CASSANDRA_DC}\""]
    interval: 5s
    timeout: 5s
    retries: 60
  deploy:
    resources:
      limits:
        memory: 512M

# Общие переменные окружения
x-environment: &common-env
  CASSANDRA_SEEDS: "cass-three-A:7000,cass-three-B:7000"
  CASSANDRA_CLUSTER_NAME: THREE_CLUSTER
  CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
  JVM_OPTS: "-Xms128M -Xmx256M -XX:+UseG1GC"

services:
  cass-three-A:
    <<: *cassandra-base
    container_name: cass-three-A
    hostname: cass-three-A
    networks:
      cassandra_three:
        ipv4_address: *ip-a
    ports: ["9041:9042", "7191:7199", "7001:7000"]
    volumes:
      - ./data/cass-three-A:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-a
      CASSANDRA_DC: LORDAERON
      CASSANDRA_RACK: LORDAERON-RACK

  cass-three-B:
    <<: *cassandra-base
    container_name: cass-three-B
    hostname: cass-three-B
    networks:
      cassandra_three:
        ipv4_address: *ip-b
    ports: ["9042:9042", "7192:7199", "7002:7000"]
    volumes:
      - ./data/cass-three-B:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-b
      CASSANDRA_DC: KALIMDOR
      CASSANDRA_RACK: KALIMDOR-RACK
    depends_on:
      cass-A: { condition: service_healthy }

  cass-three-C:
    <<: *cassandra-base
    container_name: cass-three-C
    hostname: cass-three-C
    networks:
      cassandra_three:
        ipv4_address: *ip-c
    ports: ["9043:9042", "7193:7199", "7003:7000"]
    volumes:
      - ./data/cass-three-C:/var/lib/cassandra
      - ./jvm11-server.options:/etc/cassandra/jvm11-server.options
    environment:
      <<: *common-env
      NODE_IP: *ip-c
      CASSANDRA_DC: NORTHREND
      CASSANDRA_RACK: NORTHREND-RACK
    depends_on:
      cass-B: { condition: service_healthy }
